/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package impuestovehicular;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian Lara
 */
public class jFrame extends javax.swing.JFrame {

    Vehiculo vehi = new Vehiculo();

    /**
     * Creates new form NewJFrame
     */
    public jFrame() {
        initComponents();
        btnImpuesto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAvaluo1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        cmbModelo = new javax.swing.JComboBox<>();
        cmbLinea = new javax.swing.JComboBox<>();
        cmbMarca = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cbPago = new javax.swing.JCheckBox();
        cbTraslado = new javax.swing.JCheckBox();
        cbPublico = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        btnImpuesto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtTarifa = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lbTotal = new javax.swing.JLabel();
        txtAvaluo = new javax.swing.JTextField();

        txtAvaluo1.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CALCULAR IMPUESTO");

        jLabel2.setText("Marca");

        jLabel3.setText("Linea");

        jLabel4.setText("Modelo");

        jLabel5.setText("Valor:");

        txtValor.setEditable(false);
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        cmbModelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbModeloItemStateChanged(evt);
            }
        });

        cmbLinea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLineaItemStateChanged(evt);
            }
        });
        cmbLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLineaActionPerformed(evt);
            }
        });

        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chevrolet", "Renault", "BMW", "Hino", "Hyundai", "Yamaha" }));
        cmbMarca.setSelectedIndex(-1);
        cmbMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMarcaItemStateChanged(evt);
            }
        });
        cmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Descuentos");

        cbPago.setText("Pronto pago");
        cbPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPagoActionPerformed(evt);
            }
        });

        cbTraslado.setText("Traslado de cuenta");
        cbTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrasladoActionPerformed(evt);
            }
        });

        cbPublico.setText("Publico");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnImpuesto.setText("Impuesto");
        btnImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpuestoActionPerformed(evt);
            }
        });

        jLabel8.setText("Avaluo:");

        txtTotal.setEditable(false);

        txtTarifa.setText("Tarifa");

        jLabel9.setText("Matricula");

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTotal.setText("Total valor a pagar");

        txtAvaluo.setEditable(false);
        txtAvaluo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvaluoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(cbPago)
                .addGap(74, 74, 74)
                .addComponent(cbTraslado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbPublico)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(4, 4, 4)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 152, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCalcular)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(txtTarifa)))))
                                .addGap(88, 88, 88)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtAvaluo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(124, 124, 124))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnImpuesto)
                        .addGap(110, 110, 110)
                        .addComponent(lbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtAvaluo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtTarifa))))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTraslado)
                            .addComponent(cbPago)
                            .addComponent(cbPublico))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnImpuesto)
                            .addComponent(lbTotal)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentMoved

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void cbPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPagoActionPerformed

    private void asignacion(String modelo, int precio, String tipo, String matricula) {
        //Vehiculo

        vehi.setMatricula(matricula);
        vehi.setModelo(modelo);
        vehi.setPrecio(precio);
        vehi.setTipo(tipo);

        //Impuesto       
        vehi.CalcularTarifa(precio);
        vehi.CalcularImpuesto(precio);

    }

    private boolean validar() {
        if (txtMatricula.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Debe llenar el campo de matricula! ");
            System.out.println("aaaa");
            return false;
        }
        if (cmbMarca.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la marca del vehiculo!");
            return false;
        }
        if (cmbLinea.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la linea del vehiculo!");
            return false;
        }
        return true;
    }

    @SuppressWarnings("empty-statement")
    private void cmbMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMarcaItemStateChanged
        clean();
        int index = cmbMarca.getSelectedIndex();
        String marcas[] = new String[3];

        switch (index) {
            case 0 -> {
                cmbLinea.removeAllItems();
                marcas[1] = "Spark";
                marcas[2] = "Camaro";
                break;
            }
            case 1 -> {
                cmbLinea.removeAllItems();
                marcas[1] = "Sandero";
                marcas[2] = "Logan";
                break;
            }
            case 2 -> {
                cmbLinea.removeAllItems();
                marcas[1] = "GS";
                marcas[2] = "R 1200";
                break;
            }
            case 3 -> {
                cmbLinea.removeAllItems();
                marcas[1] = "FC9J";
                marcas[2] = "Dutro";
                break;
            }
            case 4 -> {
                cmbLinea.removeAllItems();
                marcas[1] = "Accent";
                marcas[2] = "Starex";
                break;
            }
            case 5 -> {
                cmbLinea.removeAllItems();
                marcas[1] = "BWS";
                marcas[2] = "FZ";
                break;
            }
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(marcas);
        cmbLinea.setModel(modelo);
    }//GEN-LAST:event_cmbMarcaItemStateChanged

    private void cmbLineaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLineaItemStateChanged
        clean();
        if (cmbLinea.getSelectedItem() != null) {
            String item = cmbLinea.getSelectedItem().toString();
            String marcas[] = new String[2];

            switch (item) {
                case "Sandero" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2015";
                    marcas[1] = "2022";
                    break;
                }
                case "Logan" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2011";
                    marcas[1] = "2022";
                    break;
                }
                case "Spark" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2019";
                    marcas[1] = "2020";
                    break;
                }
                case "Camaro" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2010";
                    marcas[1] = "2022";
                    break;
                }
                case "BWS" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2012";
                    marcas[1] = "2020";
                    break;
                }
                case "FZ" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2020";
                    marcas[1] = "2023";
                    break;
                }
                case "GS" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2015";
                    marcas[1] = "2019";
                    break;
                }
                case "R 1200" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2014";
                    marcas[1] = "2016";
                    break;
                }
                case "Accent" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2019";
                    marcas[1] = "2003";
                    break;
                }
                case "Starex" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2008";
                    marcas[1] = "2021";
                    break;
                }
                case "FC9J" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2012";
                    marcas[1] = "2017";
                    break;
                }
                case "Dutro" -> {
                    cmbModelo.removeAllItems();
                    marcas[0] = "2012";
                    marcas[1] = "2020";
                    break;
                }

            }
            DefaultComboBoxModel modelo = new DefaultComboBoxModel(marcas);
            cmbModelo.setModel(modelo);
        }

    }//GEN-LAST:event_cmbLineaItemStateChanged

    private void cmbModeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbModeloItemStateChanged

    }//GEN-LAST:event_cmbModeloItemStateChanged

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void cmbLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLineaActionPerformed

    private void cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMarcaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (validar()) {
            if (cmbModelo.getSelectedItem() != null) {
                String modelo = cmbModelo.getSelectedItem().toString();
                String marca = cmbMarca.getSelectedItem().toString();
                String linea = cmbLinea.getSelectedItem().toString();
                String valor = "";
                String tipo = "";

                switch (marca) {
                    case "Renault" -> {
                        tipo = "Carro";
                        if (linea == "Sandero" && modelo == "2015") {
                            valor = "$38,000,000";
                        }
                        if (linea == "Sandero" && modelo == "2022") {
                            valor = "$59,700,000";
                        }
                        if (linea == "Logan" && modelo == "2011") {
                            valor = "$26,500,000";
                        }
                        if (linea == "Logan" && modelo == "2022") {
                            valor = "$64,650,000";
                        }
                        break;
                    }
                    case "Yamaha" -> {
                        tipo = "Moto";
                        if (linea == "BWS" && modelo == "2012") {
                            valor = "$4,600,000";
                        }
                        if (linea == "BWS" && modelo == "2020") {
                            valor = "$9,800,000";
                        }
                        if (linea == "FZ" && modelo == "2020") {
                            valor = "$11,500,000";
                        }
                        if (linea == "FZ" && modelo == "2023") {
                            valor = "$13,800,000";
                        }
                        break;
                    }
                    case "Hyundai" -> {
                        tipo = "Carro";
                        if (linea == "Accent" && modelo == "2019") {
                            valor = "$120,000,000";
                        }
                        if (linea == "Accent" && modelo == "2003") {
                            valor = "$65,000,000";
                        }
                        if (linea == "Starex" && modelo == "2008") {
                            valor = "$26,990,000";
                        }
                        if (linea == "Starex" && modelo == "2021") {
                            valor = "$132,000,000";
                        }
                        break;
                    }
                    case "Chevrolet" -> {
                        tipo = "Carro";
                        if (linea == "Spark" && modelo == "2019") {
                            valor = "$18,700,000";
                        }
                        if (linea == "Spark" && modelo == "2020") {
                            valor = "$36,000,000";
                        }
                        if (linea == "Camaro" && modelo == "2010") {
                            valor = "$85,000,000";
                        }
                        if (linea == "Camaro" && modelo == "2022") {
                            valor = "$195,000,0000";
                        }
                        break;
                    }
                    case "BMW" -> {
                        tipo = "Moto";
                        if (linea == "GS" && modelo == "2015") {
                            valor = "$34,000,000";
                        }
                        if (linea == "GS" && modelo == "2019") {
                            valor = "$23,400,000";
                        }
                        if (linea == "R 1200" && modelo == "2014") {
                            valor = "$55,000,000";
                        }
                        if (linea == "R 1200" && modelo == "2016") {
                            valor = "$65,000,000";
                        }
                        break;
                    }
                    case "Hino" -> {
                        tipo = "T.Publico";
                        if (linea == "FC9J" && modelo == "2012") {
                            valor = "$110,000,000";
                        }
                        if (linea == "FC9J" && modelo == "2017") {
                            valor = "$210,000,000";
                        }
                        if (linea == "Dutro" && modelo == "2012") {
                            valor = "$100,000,000";
                        }
                        if (linea == "Dutro" && modelo == "2020") {
                            valor = "$139,900,000";
                        }
                        break;
                    }
                }

                txtValor.setText(valor);
                valor = valor.replace("$", "");
                valor = valor.replace(",", "");
                asignacion(modelo, Integer.parseInt(valor), tipo, txtMatricula.getText());
                txtAvaluo.setText(vehi.impuesto);
                txtTarifa.setText("" + vehi.tarifa);
                btnImpuesto.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cbTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrasladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTrasladoActionPerformed

    private void txtAvaluoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvaluoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvaluoActionPerformed

    private void btnImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpuestoActionPerformed
        boolean isPublic = cbPublico.isSelected();
        boolean isAccounTransfer = cbTraslado.isSelected();
        boolean isPromptPay = cbPago.isSelected();
        
        vehi.AplicaDescuento(isPublic, isAccounTransfer, isPromptPay);
        txtTotal.setText(vehi.getImpuesto());
        btnImpuesto.setVisible(false);
    }//GEN-LAST:event_btnImpuestoActionPerformed

    private void clean() {
        txtValor.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnImpuesto;
    private javax.swing.JCheckBox cbPago;
    private javax.swing.JCheckBox cbPublico;
    private javax.swing.JCheckBox cbTraslado;
    private javax.swing.JComboBox<String> cmbLinea;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JComboBox<String> cmbModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField txtAvaluo;
    private javax.swing.JTextField txtAvaluo1;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JLabel txtTarifa;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
